# Setup
title:            Blake Helms
tagline:          'The digital home of Blake Helms'
description:      'The digital home of Blake Helms'
url:              https://blakehelms.net
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Blake Helms'
  url:            https://twitter.com/helmsb

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
